### PR TITLE
Fix the CS so Travis is happy with your PR too :)

### PR DESCRIPTION
**Pull request by zero-24**
hi @joaobsantos this trys to make travis a happy guy.

Traivs is our CI Server and he checks our unit tests and codestyle.

The result can be found here: https://travis-ci.org/joomla/joomla-cms/jobs/81759930

This PR should fix the issues he mention. The only thing that is left. Can you please add a usage example?

If you commit here (using the magic green button) you need to sync it back to lokal like `git pull origin staging`

After that you go to this file and add the usage example.

The third step is `git commit -am 'add the usage example'`

Than you can upload it to your patch with: `git push origin staging`

Let me know if you understand or not understand what I try to explain. ;)

### CODE REVIEW

**Comment by joaobsantos** [comment]
hi @zero-24, so let me see the unit test gave 6 errors 3 becouse of white space and the other 3 about documentation. And u are saying that i should change the code locally and use the shell to commit instead of using the green button?! Im sorry, i started using github 3 days ago, and coding 2 weeks ago... Im way over my head :(

**Comment by zero-24** [comment]
hi @joaobsantos here you can just use the grean button ;)

I mean the example. but if you can tell me a example that we can dokument i can add it to this PR and you merge it in (with the green button)

Sorry for confusing.

**Comment by joaobsantos** [comment]
oh sorry im such a noob, you're making a commit to my code.. lol Ok i'll accept you're change to the block information, but the devs in joomla sad i should passa that function there, becouse its not a satandart mysql function like for example SET.... They sad i should change it in mysql.php...

**Comment by zero-24** [comment]
ok :smile: Thanks. :+1:

**Pull request merged**
